spring.application.name=Login
spring.web.resources.static-locations=classpath:/static/,file:D:/static/
# ??????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ?????
spring.datasource.name=defaultDataSource
# ???????
spring.datasource.url=jdbc:mysql://106.53.194.250:43306/202301020206?serverTimezone=Asia/Shanghai 
# ??????&???
spring.datasource.username=202301020206
spring.datasource.password=@hnucm1254

#??Mybatis?Mapper??
mybatis.mapper-locations=classpath:mapper/*.xml

mybatis.type-aliases-package=com.hnucm.login.model

logging.level.com.hnucm.springboot = debug
